### ISSUE TITLE
Install Polymer Devtools

### ISSUE THREAD

**Issue by maasencioh** [UNArqui17i-B/FrontEnd#1]
Please update as soon as possible
  - [x] @NeillGiraldo 
  - [x] @afmesag 
  - [x] @Lawih 
  - [x] @LaurAlejandraC

**Comment by NeillGiraldo** [comment]
- [ ] Instalar Polymer - Laura Ruby
- [ ] Instalar Polymer - Laura Go
- [ ] Instalar Polymer - Miguel
- [ ] Instalar Polymer - Andres
- [ ] Instalar Polymer - Neill

**Comment by maasencioh** [comment]
what's the status in this? @UNArqui17i-B/developers
