### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by maasencioh** [UNArqui17i-B/FrontEnd#37]
Confirm and close the user session on the localstorage

**Comment by NeillGiraldo** [comment]
Will the token and exp_date be deleted after logging out?

**Comment by maasencioh** [comment]
currently it's not done like that, mainly for performance, but what do you think @UNArqui17i-B/developers ?

**Comment by NeillGiraldo** [comment]
I believe it is a must, due to the fact that if you try loggining in again, it returns a 302 error

**Comment by maasencioh** [comment]
302 it's not an error, but I'll send a 202

**Comment by maasencioh** [comment]
Follow in https://github.com/UNArqui17i-B/API-gateway/issues/8

**Comment by NeillGiraldo** [comment]
https://github.com/Polymer/polymer/issues/1550 object sub-properties should not be used
